/*

AddCustomer

Adds a new customer to the database.

The ID is auto-generated by the database.
Returns the newly created ID as a single-row result set.

Parameters:

@ContactName   - Required. Name of the contact person.
@Address       - Required. Billing/Shipping address.
@City          - Required. City name.
@Region        - Required. Region/State.
@PostalCode    - Required. Zip/Postal code.
@Country       - Required. Country name.
@PhoneNumber   - Required. Contact phone number.
@DemographicsID- Optional. Link to CustomerDemographics table.
@ContactTitle  - Optional. Job title.
@Fax           - Optional. Fax number.
@NIP           - Optional. Tax Identification Number.

Usage:

EXEC AddCustomer
    @ContactName = 'Jan Iłowski',
    @Address = 'Ul. Prosta 10',
    @City = 'Warsaw',
    @Region = 'Mazowieckie',
    @PostalCode = '00-001',
    @Country = 'Poland',
    @PhoneNumber = '+48 123 456 789';
*/

CREATE OR ALTER PROCEDURE [dbo].[AddCustomer]
    @ContactName            VARCHAR(255),
    @Address                VARCHAR(MAX),
    @City                   VARCHAR(255),
    @Region                 VARCHAR(255),
    @PostalCode             VARCHAR(16),
    @Country                VARCHAR(255),
    @PhoneNumber            VARCHAR(32),
    @CustomerDemographicsID INT = NULL,
    @ContactTitle           VARCHAR(255) = NULL,
    @Fax                    VARCHAR(32) = NULL,
    @NIP                    VARCHAR(10) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        INSERT INTO dbo.Customers (
            [CustomerDemographicsID],
            [ContactName],
            [ContactTitle],
            [Address],
            [City],
            [Region],
            [PostalCode],
            [Country],
            [PhoneNumber],
            [Fax],
            [NIP]
        )
        VALUES (
            @CustomerDemographicsID,
            @ContactName,
            @ContactTitle,
            @Address,
            @City,
            @Region,
            @PostalCode,
            @Country,
            @PhoneNumber,
            @Fax,
            @NIP
        );

        -- Return the new ID to the application
        SELECT CAST(SCOPE_IDENTITY() AS INT) AS [ID];
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END;
GO
